### ISSUE TITLE
global.XMLHttpRequest is not a constructor

### ISSUE THREAD

**Issue by peculiarity** [request/request-promise-native#14]
I'm building a small library.

- Using following versions:
```javascript
 "request": "^2.83.0",
 "request-promise-native": "^1.0.5",
```

- Injecting the package as follows:

```javascript
import request from 'request-promise-native';
```

Building UMD package so it could be used all kinds of ways. Browser and Node. Using webpack as a bundle tool.

When I inject the output as script tag and use use instance of the library and call methods ( using `request` ) everything works fine.

When I used node repl to test when I require my output file I receive this.

```javascript
TypeError: global.XMLHttpRequest is not a constructor
```

**Comment by brettz9** [comment]
FWIW, I came across this error using node-fetch (since 2.1.2 the problematic code gets added when one uses `import` instead of `require`; I discovered this for myself after reading https://github.com/calvinmetcalf/rollup-plugin-node-builtins/issues/25 ; )... I suppose one might be able to avoid this through configuration of their Rollup/bundling pipeline by explicitly avoiding the `browser` field in `package.json` for Node code, etc., but I went with the quick-and-dirty solution of just using `require` over `import` for the responsible code...

**Comment by analog-nico** [comment]
I can’t explain your `TypeError` @peculiarity . It is something that originates from your particular environment.

In general, if you use `request-promise-native` client-side then you will have to polyfill many core node.js libraries. `request-promise-native` is written for node.js and thus it is not straight forward to use it outside of node. It is possible though. Many users reported that they successfully use it with webpack or browserify. However, I can’t provide official support unfortunately.
