### ISSUE TITLE
Embed request as dependency

### ISSUE THREAD

**Issue by moehlone** [request/request-promise-native#16]
Hi there,

why is `request` not installed as dependency in `request-promise-native`? I think it is overhead to install it manually when only using `request-promise-native` - people who use dependency checkers will have failing pipelines, because it is unused. Or is there another reason?

Best
Philipp

**Comment by mastermatt** [comment]
This comment/question/request is better suited for the https://github.com/request/promise-core repo. That being said, my two cents:

Setting `request` as a peer would changes the way npm saves that lib in the dependency graph. In the case of simple dep graphs, having a dep next to versus nested under makes no difference. However, if you consider this lib a plugin to the `request` ecosystem (which I believe the core devs do) then it does make a difference because as soon as you add more than one plugin, the behavior changes in how those plugins interact. 

If the core devs do not consider this lib a plugin, then `request` should be added as a dep of `promise-core` and that would be that. 

As a note: back when the dependancies of this repo were defined (pre-npm3) `peerDependencies` would auto-install just like `dependencies`.

**Comment by analog-nico** [comment]
Great thoughts @mastermatt ! Since you mention the pre-npm3 era, it’s not a relict from that time. In a few words, npm does not have the perfect type of dependency that would suit the relationship of both libs. For further details, please have a look at my [Was moving request to peerDependencies the best choice?](https://github.com/request/request-promise/issues/142) issue.
